name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

<<<<<<< HEAD
    services:
      docker:
        image: docker:20.10.9
        options: --privileged
=======
    container:
      image: maven:3.8.6-openjdk-8  # Use a custom Docker image with Java 8 and Maven 3.8.6
>>>>>>> parent of 73f5d61 (Update maven.yml)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-GOL-webApp
        path: gameoflife-web/target/gameoflife.war
<<<<<<< HEAD

  build-docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-docker-image .
=======
>>>>>>> parent of 73f5d61 (Update maven.yml)
