name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.9
        options: --privileged
    container:
      image: maven:3.8.6-openjdk-8  # Use a custom Docker image with Java 8 and Maven 3.8.6

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-GOL-webApp
        path: gameoflife-web/target/gameoflife.war
        

  build-docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download WAR artifact
      uses: actions/download-artifact@v2
      with:
        name: my-GOL-webApp
        path: gameoflife-web/target/

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u krtk94 --password-stdin
      env:
        DOCKER_USERNAME: krtk94
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build Docker Image
      run: docker build -t gol:1.0 . 

    - name: Push Docker Image to dockerhub
      run: docker push krtk94/gameoflife:1.0

